version: "3.7"
services:
  coaching:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: coaching
    stdin_open: true
    volumes:
      - ./:/var/www/html/coaching
      - /var/www/html/coaching/node_modules
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.coaching.rule=Host(`coaching.dndnew.hu`)"
      - "traefik.http.routers.coaching.entrypoints=websecure"
      - "traefik.http.routers.coaching.tls.certresolver=myresolver"
    ports:
      - 3000:3000
    networks:
      - traefik-public
    command: npm run start

networks:
  traefik-public:
    external: true
